services:
  - type: web
    name: soft-ui-node-backend
    env: node
    plan: free
    region: singapore
    buildCommand: "./api-server-nodejs/build.sh"
    startCommand: |
      cd api-server-nodejs
      npm run start-node
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: soft_ui_db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

  - type: web
    name: soft-ui-react-frontend
    plan: free
    env: node
    region: singapore
    buildCommand: "./react-ui/build.sh"
    startCommand: |
      cd react-ui
      yarn start:prod
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: REACT_APP_BACKEND_SERVER
        value: "https://soft-ui-node-backend.onrender.com/api/"


databases:
  - name: soft_ui_db
    databaseName: soft_ui_db
    user: soft_ui_db
    plan: free
    region: singapore